### ISSUE TITLE
About cross agreement score

### ISSUE THREAD

**Issue by YangJae96** [yoonkicho/PPLR#9]
Hello, thanks for the great work.

I have a question about the paper.

Alternatively, I think just the feature L2-normed cosine similarity between samples could also be used for ranking.
Why did you measured cross agreement score based on Jaccard similarity?

**Comment by yoonkicho** [comment]
Thank you for your interest and sorry for the late reply.

The cosine similarity between global and part features captures the relationship between features of a "single" image.
On the other hand, the jaccard similarity between ranked lists can capture the similarity between k-nearest neighbors (= also consider other images rather than a single image) of each feature.
The jaccard similarity would be a better option to measure the noise of pseudo-labels, because clustering computes pseudo-labels by considering feature distances between images.
